### ISSUE TITLE
rfc3339 6.2 is not supported on this platform

### ISSUE THREAD

**Issue by BastianZim** [conda-forge/rfc3339-feedstock#5]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

Hi,

I'm getting this error in another build: `rfc3339 6.2 is not supported on this platform`

After some online searching, it seems that that could maybe be fixed by rebuilding the package, but not sure. Would you mind rerendering it and releasing a new version?

Info: https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=1008089&view=logs&jobId=656edd35-690f-5c53-9ba3-09c10d0bea97&j=656edd35-690f-5c53-9ba3-09c10d0bea97&t=986b1512-c876-5f92-0d81-ba851554a0a3

Thanks!

### Installed packages

```shell
Azure Pipelines
```

### Environment info

```shell
Azure pipelines
```

**Comment by kynan** [comment]
Sure, worth a try I suppose :)

@conda-forge-admin, please rerender

**Comment by kynan** [comment]
@BastianZim Done, please confirm if this has resolved the issue.

**Comment by BastianZim** [comment]
That fixed it, thank you!
